Tech 231
distributed-technologies/mukube-ingress pull request #1
Opened 2021-03-09 15:04 UTC by lynderup

Initial helm chart. Only http routes at the moment

2021-03-11 11:45 UTC, jacobcrawford requested changes
Looks good. A few questions and change requests.

2021-03-11 11:45 UTC, jacobcrawford commented on chart/values.yaml
> +
too many whitespace lines.

2021-03-11 11:45 UTC, jacobcrawford commented on chart/templates/service.yaml
> +# Makes a nested dictionary, from .Values.ports, with the structure ServiceType->PortName->PortConfig
Maybe explain the structure of the dictionary in yaml or json format.

2021-03-11 11:45 UTC, jacobcrawford commented on chart/values.yaml
> +  name: traefik
I think we need to specify a version of the traefik image.

2021-03-11 11:45 UTC, jacobcrawford commented on chart/values.yaml
> +  tag: ""
"tag" is not used anywhere.

2021-03-11 11:45 UTC, jacobcrawford commented on chart/values.yaml
> +nameOverride: ""
The use of nameOverride and fullnameOverride is unclear to me. Can you make a comment infile?

2021-03-11 11:45 UTC, jacobcrawford commented on chart/templates/service.yaml
> +# Makes a nested dictionary, from .Values.ports, with the structure ServiceType->PortName->PortConfig
Maybe give an example of a yaml tree input and output of this.

2021-03-11 12:23 UTC, MartinSchmidt requested changes
There are a series of comments I agree should be changed.

2021-03-11 12:23 UTC, MartinSchmidt commented on chart/values.yaml
> +  name: traefik
I agree.

2021-03-11 12:23 UTC, MartinSchmidt commented on chart/values.yaml
> +  tag: ""
remove the tag or use {name}:{tag} in the code.

2021-03-11 12:23 UTC, MartinSchmidt commented on chart/Chart.yaml
> +# A chart can be either an 'application' or a 'library' chart.
Remove all the boilerplate comments.

2021-03-16 10:05 UTC, jacobcrawford approved these changes
Looks good! :D

2021-03-18 11:47 UTC, MartinSchmidt approved these changes

2021-03-19 08:38 UTC, merged